fehlerhaft (mika überprüfen)
Traceback (most recent call last):
  File "c:\Users\tomas.lang\Documents\GitHub\ag-Assistent\assistent-cli.py", line 2, in <module>
    core.loop()
  File "c:\Users\tomas.lang\Documents\GitHub\ag-Assistent\core\__init__.py", line 84, in loop
    a = request(r)
        ^^^^^^^^^^
  File "c:\Users\tomas.lang\Documents\GitHub\ag-Assistent\core\__init__.py", line 93, in request
    return plugin_commands(r)
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\tomas.lang\Documents\GitHub\ag-Assistent\core\__init__.py", line 65, in plugin_commands
    case 1: return class_runner(d[list(d.keys())[0]])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tomas.lang\Documents\GitHub\ag-Assistent\core\__init__.py", line 53, in class_runner
    r = c()
        ^^^
TypeError: rechnen.qwurzel() missing 1 required positional argument: 'input'